/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/venues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공연장 목록 조회
     * @description 공연장 목록을 조회합니다.
     */
    get: operations["getAllVenues"];
    put?: never;
    /**
     * 공연장 생성
     * @description 공연장과 좌석을 생성합니다.
     */
    post: operations["createVenueDetails"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공연 회차 목록 조회
     * @description 예정 회차와 지난 회차를 구분하고, 각 그룹을 공연 시작 시각이 빠른 순서로 반환합니다.
     */
    get: operations["getPerformances"];
    put?: never;
    /**
     * 공연 회차 생성
     * @description 새로운 공연 회차를 생성합니다.
     */
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/concerts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 콘서트 목록 조회
     * @description 최신 생성순으로 콘서트 목록을 반환합니다.
     */
    get: operations["getConcerts"];
    put?: never;
    /**
     * 콘서트 생성
     * @description 새로운 콘서트를 생성합니다.
     */
    post: operations["create_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 인증 토큰 재발급
     * @description refresh_token 쿠키를 검증하여 새 access_token과 refresh_token 쿠키를 발급합니다. 기존 Refresh Token은 즉시 무효화됩니다.
     */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description 유효한 refresh_token이 있으면 서버에서 무효화하고, 항상 인증 쿠키를 만료합니다.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/venues/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공연장 상세 조회
     * @description 공연장과 좌석 정보를 조회합니다.
     */
    get: operations["getVenueDetails"];
    put?: never;
    post?: never;
    /**
     * 공연장 삭제
     * @description 공연장과 좌석을 삭제합니다.
     */
    delete: operations["deleteVenue"];
    options?: never;
    head?: never;
    /**
     * 공연장 일괄 생성 / 수정 / 삭제
     * @description 공연장과 좌석을 일괄적으로 생성, 수정, 삭제합니다. 요청에 포함된 좌석 정보는 공연장에 대한 좌석 정보를 완전히 대체합니다. 즉, 요청에 포함되지 않은 좌석은 삭제됩니다.
     */
    patch: operations["updateVenueDetails"];
    trace?: never;
  };
  "/api/performances/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공연 회차 상세 조회
     * @description 공연 회차의 상세 정보를 반환합니다.
     */
    get: operations["getPerformance"];
    put?: never;
    post?: never;
    /**
     * 공연 회차 삭제
     * @description 기존 공연 회차를 삭제합니다.
     */
    delete: operations["delete"];
    options?: never;
    head?: never;
    /**
     * 공연 회차 수정
     * @description 기존 공연 회차 정보를 수정합니다.
     */
    patch: operations["update"];
    trace?: never;
  };
  "/api/concerts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 콘서트 상세 조회
     * @description 콘서트 상세 정보와 예정 회차를 우선으로 정렬한 공연 회차 목록을 반환합니다.
     */
    get: operations["getConcertDetail"];
    put?: never;
    post?: never;
    /**
     * 콘서트 삭제
     * @description 기존 콘서트를 삭제합니다.
     */
    delete: operations["delete_1"];
    options?: never;
    head?: never;
    /**
     * 콘서트 수정
     * @description 기존 콘서트 정보를 수정합니다.
     */
    patch: operations["update_1"];
    trace?: never;
  };
  "/api/performances/{id}/seats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공연 좌석 상태 목록 조회
     * @description 공연 회차의 좌석 상태 목록을 반환합니다.
     */
    get: operations["getSeatsStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/oauth/{oauth_provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * OAuth 인증 URL로 리다이렉트
     * @description 지원하는 OAuth provider로 요청 시 인증 URL로 리다이렉트합니다.
     */
    get: operations["getAuthorizationUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/oauth/{oauth_provider}/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * OAuth 인증 콜백 처리
     * @description OAuth 인증 후 콜백을 처리하고, 로그인 성공 시 access_token과 refresh_token을 쿠키에 저장하고 프론트엔드로 리다이렉트합니다. 로그인 실패 시 에러 코드와 함께 프론트엔드로 리다이렉트합니다.
     */
    get: operations["handleOAuthCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 정보 조회
     * @description 로그인한 사용자의 정보를 반환합니다.
     */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateVenueDetailRequest: {
      venue: components["schemas"]["CreateVenueRequest"];
      venueSeats: components["schemas"]["CreateVenueSeatRequest"][];
    };
    CreateVenueRequest: {
      name: string;
      address: string;
      description: string | null;
      width: number;
      height: number;
      stagePositionX: number;
      stagePositionY: number;
      stageWidth: number;
      stageHeight: number;
    };
    CreateVenueSeatRequest: {
      sectionName: string;
      /** Format: int32 */
      seatNumber: number;
      seatLabel: string;
      /** Format: int32 */
      price: number;
      positionX: number;
      positionY: number;
    };
    SuccessVenueDetailResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["VenueDetailResponse"];
    };
    VenueDetailResponse: {
      venue: components["schemas"]["VenueResponse"];
      venueSeats: components["schemas"]["VenueSeatResponse"][];
    };
    VenueResponse: {
      /** Format: int64 */
      id: number;
      name: string;
      address: string;
      description: string | null;
      width: number;
      height: number;
      stagePositionX: number;
      stagePositionY: number;
      stageWidth: number;
      stageHeight: number;
      /** Format: date-time */
      createdAt: string;
    };
    VenueSeatResponse: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      venueId: number;
      sectionName: string;
      /** Format: int32 */
      seatNumber: number;
      seatLabel: string;
      /** Format: int32 */
      price: number;
      positionX: number;
      positionY: number;
      /** Format: date-time */
      createdAt: string;
    };
    CreatePerformanceRequest: {
      /** Format: int64 */
      concertId: number;
      name: string;
      /** Format: date-time */
      startsAt: string;
      /** Format: date-time */
      bookingOpensAt: string | null;
    };
    PerformanceResponse: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      concertId: number;
      /** Format: int64 */
      venueId: number;
      name: string;
      /** Format: date-time */
      startsAt: string;
      /** Format: date-time */
      bookingOpensAt: string | null;
      /** Format: date-time */
      createdAt: string;
      status: components["schemas"]["PerformanceStatus"];
    };
    /** @enum {string} */
    PerformanceStatus: "UPCOMING" | "AVAILABLE" | "SOLD_OUT" | "ENDED";
    SuccessPerformanceResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["PerformanceResponse"];
    };
    /** @enum {string} */
    ConcertGenre: "BALLAD" | "ROCK_METAL" | "RAP_HIPHOP" | "JAZZ_SOUL" | "TROT" | "INTERNATIONAL_ARTIST" | "FESTIVAL" | "INDIE";
    CreateConcertRequest: {
      /** Format: int64 */
      venueId: number;
      title: string;
      genre: components["schemas"]["ConcertGenre"];
      posterUrl: string | null;
      description: string | null;
    };
    ConcertResponse: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      venueId: number;
      title: string;
      genre: components["schemas"]["ConcertGenre"];
      venueName: string;
      posterUrl: string | null;
      description: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    SuccessConcertResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["ConcertResponse"];
    };
    EmptySuccess: {
      /** @enum {boolean} */
      success: true;
      /** @enum {string|null} */
      data: null;
    };
    UpdateVenueDetailRequest: {
      venue: components["schemas"]["UpdateVenueRequest"] | null;
      venueSeats: components["schemas"]["UpdateVenueSeatRequest"][] | null;
      deletedSeatIds: number[] | null;
    };
    UpdateVenueRequest: {
      name?: string;
      address?: string;
      description?: string | null;
      width?: number;
      height?: number;
      stagePositionX?: number;
      stagePositionY?: number;
      stageWidth?: number;
      stageHeight?: number;
    };
    UpdateVenueSeatRequest: {
      /** Format: int64 */
      id: number | null;
      sectionName: string;
      /** Format: int32 */
      seatNumber: number;
      seatLabel: string;
      /** Format: int32 */
      price: number;
      positionX: number;
      positionY: number;
    };
    UpdatePerformanceRequest: {
      name?: string;
      /** Format: date-time */
      startsAt?: string;
      /** Format: date-time */
      bookingOpensAt?: string | null;
    };
    UpdateConcertRequest: {
      title?: string;
      genre?: components["schemas"]["ConcertGenre"];
      posterUrl?: string | null;
      description?: string | null;
    };
    SuccessListVenueResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["VenueResponse"][];
    };
    SuccessListPerformanceResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["PerformanceResponse"][];
    };
    HeldSeat: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      expiresAt: string;
    };
    PerformanceSeatListResponse: {
      /** Format: date-time */
      serverTime: string;
      bookedSeats: number[];
      heldSeats: components["schemas"]["HeldSeat"][];
    };
    SuccessPerformanceSeatListResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["PerformanceSeatListResponse"];
    };
    ConcertListResponse: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      venueId: number;
      title: string;
      genre: components["schemas"]["ConcertGenre"];
      venueName: string;
      posterUrl: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    SuccessListConcertListResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["ConcertListResponse"][];
    };
    ConcertDetailResponse: {
      concert: components["schemas"]["ConcertResponse"];
      performances: components["schemas"]["PerformanceResponse"][];
    };
    SuccessConcertDetailResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["ConcertDetailResponse"];
    };
    CurrentUserResponse: {
      /** Format: int64 */
      id: number;
      email: string;
      nickname: string;
      profileImageUrl: string | null;
      role: components["schemas"]["UserRole"];
      oauthAccounts: string[];
    };
    SuccessCurrentUserResponse: {
      /** @enum {boolean} */
      success: true;
      data: components["schemas"]["CurrentUserResponse"];
    };
    /** @enum {string} */
    UserRole: "USER" | "ADMIN";
    Error: {
      /** Format: int32 */
      code: number;
      message: string;
    };
    Failure: {
      /**
       * @example false
       * @enum {boolean}
       */
      success: false;
      error: components["schemas"]["Error"];
    };
    /** @enum {string} */
    OAuthErrorCode:
      | "OAUTH_ACCESS_DENIED"
      | "OAUTH_STATE_MISSING"
      | "OAUTH_STATE_MISMATCH"
      | "OAUTH_STATE_EXPIRED"
      | "OAUTH_CODE_EXCHANGE_FAILED"
      | "OAUTH_PROFILE_FETCH_FAILED"
      | "OAUTH_ACCOUNT_CONFLICT";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAllVenues: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공연장 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessListVenueResponse"];
        };
      };
    };
  };
  createVenueDetails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateVenueDetailRequest"];
      };
    };
    responses: {
      /** @description 공연장 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessVenueDetailResponse"];
        };
      };
      /** @description 잘못된 요청입니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 400,
           *         "message": "잘못된 요청입니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  getPerformances: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공연 회차 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessListPerformanceResponse"];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePerformanceRequest"];
      };
    };
    responses: {
      /** @description 공연 회차 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessPerformanceResponse"];
        };
      };
      /** @description 잘못된 요청입니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 400,
           *         "message": "잘못된 요청입니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 콘서트를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  getConcerts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 콘서트 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessListConcertListResponse"];
        };
      };
    };
  };
  create_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateConcertRequest"];
      };
    };
    responses: {
      /** @description 콘서트 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessConcertResponse"];
        };
      };
      /** @description 잘못된 요청입니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 400,
           *         "message": "잘못된 요청입니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description 새 인증 쿠키 발급 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmptySuccess"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description CSRF 검증 실패 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description 로그아웃 및 인증 쿠키 삭제 완료 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmptySuccess"];
        };
      };
      /** @description CSRF 검증 실패 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  getVenueDetails: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공연장 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessVenueDetailResponse"];
        };
      };
      /** @description 공연장을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  deleteVenue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공연장 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmptySuccess"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 공연장을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 공연이 등록된 공연장 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 409,
           *         "message": "예상치 못한 충돌이 발생했습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  updateVenueDetails: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateVenueDetailRequest"];
      };
    };
    responses: {
      /** @description 공연장 일괄 생성 / 수정 / 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessVenueDetailResponse"];
        };
      };
      /** @description 잘못된 요청입니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 400,
           *         "message": "잘못된 요청입니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 공연장 또는 좌석을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  getPerformance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공연 회차 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessPerformanceResponse"];
        };
      };
      /** @description 공연 회차를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공연 회차 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmptySuccess"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 공연 회차를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePerformanceRequest"];
      };
    };
    responses: {
      /** @description 공연 회차 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessPerformanceResponse"];
        };
      };
      /** @description 잘못된 요청입니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 400,
           *         "message": "잘못된 요청입니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 공연 회차 또는 콘서트를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  getConcertDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 콘서트 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessConcertDetailResponse"];
        };
      };
      /** @description 콘서트를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  delete_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 콘서트 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmptySuccess"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 콘서트를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  update_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateConcertRequest"];
      };
    };
    responses: {
      /** @description 콘서트 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessConcertResponse"];
        };
      };
      /** @description 잘못된 요청입니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 400,
           *         "message": "잘못된 요청입니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 접근 권한이 필요합니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 403,
           *         "message": "접근 권한이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
      /** @description 콘서트를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  getSeatsStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공연 좌석 상태 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessPerformanceSeatListResponse"];
        };
      };
      /** @description 공연 회차를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 404,
           *         "message": "대상을 찾을 수 없습니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
  getAuthorizationUrl: {
    parameters: {
      query?: {
        /** @description OAuth 인증 후 리다이렉트할 프론트엔드 URL. 기본값은 '/'입니다. */
        redirect_uri?: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider 이름. */
        oauth_provider: "kakao" | "naver" | "google" | "github";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OAuth 인증 페이지로 리다이렉트 */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  handleOAuthCallback: {
    parameters: {
      query?: {
        code?: string;
        state?: string;
        error?: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider 이름. */
        oauth_provider: "kakao" | "naver" | "google" | "github";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 로그인 성공 또는 실패 후 프론트엔드로 리다이렉트 */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 현재 로그인한 사용자 정보 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessCurrentUserResponse"];
        };
      };
      /** @description 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "error": {
           *         "code": 401,
           *         "message": "인증이 필요합니다."
           *       }
           *     }
           */
          "application/json": components["schemas"]["Failure"];
        };
      };
    };
  };
}
